# Generated by Django 4.1.7 on 2023-03-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attach1_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='attach1_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
