# Generated by Django 4.1.7 on 2023-03-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_attach1_link_post_attach1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attach1_type',
            field=models.CharField(blank=True, choices=[('homework', 'Homework'), ('test', 'Test')], default='homework', max_length=25),
        ),
    ]
