# Generated by Django 4.1.7 on 2023-03-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_post_attach1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attach2_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='attach2_type',
            field=models.CharField(blank=True, choices=[('homework', 'Homework'), ('test', 'Test')], default='homework', max_length=25),
        ),
    ]
