# Generated by Django 4.1.7 on 2023-03-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_attach2_link_post_attach2_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attach3_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='attach3_type',
            field=models.CharField(blank=True, choices=[('homework', 'Homework'), ('test', 'Test')], default='homework', max_length=25),
        ),
    ]
