# Generated by Django 4.1.7 on 2023-03-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profile_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attach1_type',
            field=models.CharField(blank=True, choices=[('homework', 'Homework'), ('test', 'Test'), ('link', 'Link')], default='homework', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='attach2_type',
            field=models.CharField(blank=True, choices=[('homework', 'Homework'), ('test', 'Test'), ('link', 'Link')], default='homework', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='attach3_type',
            field=models.CharField(blank=True, choices=[('homework', 'Homework'), ('test', 'Test'), ('link', 'Link')], default='homework', max_length=25),
        ),
    ]
