# Generated by Django 4.1.7 on 2023-03-05 12:08

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_post_attach1_type_alter_post_attach2_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('post_id', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('username', models.CharField(max_length=100)),
                ('username_image', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images')),
                ('username_name', models.CharField(blank=True, max_length=100)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
