# Generated by Django 4.1.7 on 2023-03-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_post_no_of_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username_image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images'),
        ),
    ]
