# Generated by Django 4.1.7 on 2023-03-05 12:51

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_comment_username_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('comment_id', models.CharField(max_length=500)),
                ('post_id', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('username', models.CharField(max_length=100)),
                ('username_image', models.ImageField(blank=True, null=True, upload_to='comment_images')),
                ('username_name', models.CharField(blank=True, max_length=100)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replys',
            },
        ),
    ]
