# Generated by Django 4.1.7 on 2023-03-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_comment_no_of_replys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='post_id',
        ),
    ]
