# Generated by Django 4.1.7 on 2023-03-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_reply_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='replyed_to',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
