# Generated by Django 4.1.7 on 2023-03-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_reply_replyed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_to',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
