# Generated by Django 4.1.7 on 2023-03-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_comment_commented_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='comment_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
