# Generated by Django 4.1.7 on 2023-03-06 17:30

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_reply_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('activity_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('lesson_name', models.CharField(blank=True, max_length=100)),
                ('activity_type', models.CharField(blank=True, choices=[('charge', 'Charge'), ('purchase', 'Purchase')], default='charge', max_length=25)),
                ('purchase_type', models.CharField(blank=True, choices=[('code', 'Code'), ('wallet', 'Wallet')], default='wallet', max_length=25)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
