# Generated by Django 4.1.7 on 2023-03-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='money',
            field=models.IntegerField(default='0'),
        ),
    ]
