# Generated by Django 4.1.7 on 2023-03-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_activity_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('charge', 'Charge'), ('purchase', 'Purchase')], max_length=25),
        ),
        migrations.AlterField(
            model_name='activity',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('code', 'Code'), ('wallet', 'Wallet')], max_length=25),
        ),
    ]
