# Generated by Django 4.1.7 on 2023-03-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_activity_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='wallet',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
