# Generated by Django 4.1.7 on 2023-03-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_activity_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='school',
        ),
    ]
